"""empty message

Revision ID: ebc6fa8e1e42
Revises: 245119db9b4b
Create Date: 2018-10-26 15:37:44.017524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc6fa8e1e42'
down_revision = '245119db9b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_title', sa.String(length=64), nullable=True),
    sa.Column('b_content', sa.String(length=512), nullable=True),
    sa.Column('b_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['b_user'], ['blog_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_model')
    # ### end Alembic commands ###
