"""empty message

Revision ID: ec5676d6bf4c
Revises: d73493331068
Create Date: 2018-10-25 22:13:33.973280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5676d6bf4c'
down_revision = 'd73493331068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hello')
    # ### end Alembic commands ###
