"""empty message

Revision ID: f626e88ced1e
Revises: ebc6fa8e1e42
Create Date: 2018-10-26 16:38:26.575047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f626e88ced1e'
down_revision = 'ebc6fa8e1e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heart_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_user', sa.Integer(), nullable=True),
    sa.Column('h_blog', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['h_blog'], ['blog_model.id'], ),
    sa.ForeignKeyConstraint(['h_user'], ['blog_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heart_model')
    # ### end Alembic commands ###
